en_m4_b7_b6_b5_r152_i800 = [
  # b7,
  {
    'is_20191st': False,
    'module': 'efficientnet_gem_fc_face',
    'model_name': 'class_efficientnet_b7_gem_fc_arcface2_1head',
    'out_dir': 'v2x_sgd_ls_aug3b_norm1_0918_class_efficientnet_b7_gem_fc_arcface2_1head_i736',
    'predict_epoch': '26.80',
    'img_size': 800,
    'batch_size': 4,
    'num_classes': 81313,
    'in_channels': 3,
    'preprocessing': True,
    'weight': 0.6,
  },
  {
    'is_20191st': False,
    'module': 'efficientnet_gem_fc_face',
    'model_name': 'class_efficientnet_b6_gem_fc_arcface2_1head',
    'out_dir': 'v2x_sgd_ls_aug3b_norm1_0919_class_efficientnet_b6_gem_fc_arcface2_1head_i736',
    'predict_epoch': '21.70',
    'img_size': 800,
    'batch_size': 4,
    'num_classes': 81313,
    'in_channels': 3,
    'preprocessing': True,
    'weight': 0.2,
  },
  {
    'is_20191st': False,
    'module': 'efficientnet_gem_fc_face',
    'model_name': 'class_efficientnet_b5_gem_fc_arcface2_1head',
    'out_dir': 'v2x_sgd_ls_aug3b_norm1_0918_class_efficientnet_b5_gem_fc_arcface2_1head_i736',
    'predict_epoch': '19.30',
    'img_size': 800,
    'batch_size': 4,
    'num_classes': 81313,
    'in_channels': 3,
    'preprocessing': True,
    'weight': 0.1,
  },
  {
    'is_20191st': False,
    'module': 'resnet_gem_fc_face',
    'model_name': 'class_resnet152_gem_fc_arcface_1head',
    'out_dir': 'v2x_sgd_ls_aug3b_norm1_0919_class_resnet152_gem_fc_arcface_1head_i736',
    'predict_epoch': '17.90',
    'img_size': 800,
    'batch_size': 4,
    'num_classes': 81313,
    'in_channels': 3,
    'preprocessing': True,
    'weight': 0.1,
  },
]